spring:
  kafka:
    admin:
      properties:
        spring:
          json:
            value.default.type: net.zerotodev.api.consumer.domain.User
  application:
    name: kafka-consumer
server:
  port: 9091
